language: java
jdk:
- oraclejdk8

env:
  global:
  - GH_REF: github.com/sergeyBulygin/Java_a_to_z.git
  - secure: AAAAB3NzaC1yc2EAAAADAQABAAABAQDyrboMyJgiuziWwcUsHO7tCfVxqRnRVX2jfJHDmrpEnV+X5Y2k0NIYy3vIgMPkkv6RFv8I44gb6pPHuxHmmtFIxLDa1l2eOtIcb7WhjxnGqOEmeBQPcJ8FfDL+joyxBQhnEBnUhc9icMwoQkaemQzEu+vW7zBLUTiksUzFVNmYjVdnVE2iQEcKpwqNOjFgKxwg5G4suwrA//9c7Avc8G2OPFNULmkZ8XgoBKVAZs/l/KoEGU7oLwmvHyEFyxrfJIjCOjQuwdr99Lf9DnMcMMPbzTPzkNaC/fmYv4S/TJDjuXu+6+CRnH6aaCeSFMikNLszkB7LHKEs2MedhLqYg20D
  
  
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

# default install command is just "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -e

after_success:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
- bash update-ghpages.sh

# use latest java version available instead of travis default
addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email:
    - sergteletrade@gmail.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3319623945358a093a6f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

sudo: false # route the build to the container-based infrastructure for a faster build
